<?php
/**
 * @file
 * Hooks and api functions for Site API Key functionality.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() on behalf of site_api_key.module.
 * @see \Array method Array at Array
 */
function site_api_key_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
    $form['site_api'] = array(
      '#type' => 'details',
      '#title' => t('Site API information'),
      '#open' => TRUE,
    );
    $form['site_api']['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),'#description' => t('Please enter site API key'),
      '#maxlength' => 64,
      '#size' => 64,
      '#default_value' => \Drupal::config('site_api_key.config')->get('siteapikey'),
      '#weight' => '0',
    ];
    $form['actions']['submit']['#value'] = t('Update Configuration');
    $form['#submit'][] = 'site_api_submit';
}

function site_api_submit(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('site_api_key.config');

  // Set and save new message value.
  $config->set('siteapikey', $form_state->getValue('siteapikey'))->save();

  drupal_set_message(t('Site API Key @siteapikey has been saved', array('@siteapikey' => $form_state->getValue('siteapikey'))));
}
